from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QML_CMAKE = ROOT / "src" / "declarative" / "qml" / "qml.cmake"
UTIL_CMAKE = ROOT / "src" / "declarative" / "util" / "util.cmake"
DOC_MD = ROOT / "docs" / "ai" / "implementation" / "2026-04-05-bml-script-api-manifest.md"
DOC_JSON = ROOT / "docs" / "ai" / "implementation" / "2026-04-05-bml-script-api-manifest.json"

HEADER_RE = re.compile(r"\$\{CMAKE_CURRENT_SOURCE_DIR\}/(?:qml|util)/([^\s)]+\.h)")
QSCRIPT_INCLUDE_RE = re.compile(r"#include\s+<([^>]*QtScript/[^>]+|[^>]*qscript[^>]+)>")
QSCRIPT_IDENT_RE = re.compile(r"\b(QScript[A-Za-z0-9_]+)\b")
PRIVATE_BRIDGE_TOKENS = {
    "qscriptdeclarativeclass_p.h",
    "private/qscriptdeclarativeclass_p.h",
    "QScriptDeclarativeClass",
}
PUBLIC_HEADER_HINTS = {
    "qdeclarativecomponent.h",
    "qdeclarativecontext.h",
    "qdeclarativeengine.h",
    "qdeclarativeexpression.h",
    "qdeclarativelistmodel_p.h",
    "qdeclarativelistmodelworkeragent_p.h",
    "qdeclarativexmllistmodel_p.h",
}


def extract_headers(cmake_path: Path, block_name: str) -> list[Path]:
    text = cmake_path.read_text(encoding="utf-8", errors="ignore")
    match = re.search(rf"set\({block_name}(.*?)\n\)", text, flags=re.S)
    if not match:
        return []
    block = match.group(1)
    headers = [cmake_path.parent / rel for rel in HEADER_RE.findall(block)]
    return headers


def header_summary(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    includes = sorted(set(QSCRIPT_INCLUDE_RE.findall(text)))
    identifiers = Counter(QSCRIPT_IDENT_RE.findall(text))
    return {
        "file": path.relative_to(ROOT / "src" / "declarative").as_posix(),
        "includes": includes,
        "identifiers": dict(sorted(identifiers.items())),
        "uses_private_bridge": any(token in text for token in PRIVATE_BRIDGE_TOKENS),
    }


def main() -> None:
    public_headers = extract_headers(QML_CMAKE, "DECLARATIVE_INCLUDES") + extract_headers(UTIL_CMAKE, "DECLARATIVE_INCLUDES")
    private_headers = extract_headers(QML_CMAKE, "DECLARATIVE_PRIVATE_INCLUDES") + extract_headers(UTIL_CMAKE, "DECLARATIVE_PRIVATE_INCLUDES")

    public_data = [header_summary(path) for path in public_headers if path.exists()]
    private_data = [header_summary(path) for path in private_headers if path.exists()]

    public_script_headers = [item for item in public_data if item["includes"] or item["identifiers"]]
    private_script_headers = [item for item in private_data if item["includes"] or item["identifiers"]]

    public_include_counter: Counter[str] = Counter()
    private_include_counter: Counter[str] = Counter()
    public_ident_counter: Counter[str] = Counter()
    private_ident_counter: Counter[str] = Counter()

    for item in public_script_headers:
        for inc in item["includes"]:
            public_include_counter[inc] += 1
        public_ident_counter.update(item["identifiers"])

    for item in private_script_headers:
        for inc in item["includes"]:
            private_include_counter[inc] += 1
        private_ident_counter.update(item["identifiers"])

    public_manifest = {
        "headers": [item["file"] for item in public_script_headers],
        "qtscript_includes": sorted(public_include_counter),
        "qtscript_identifiers": sorted(public_ident_counter),
        "notable_public_headers": [item["file"] for item in public_script_headers if Path(item["file"]).name in PUBLIC_HEADER_HINTS],
    }
    private_manifest = {
        "headers": [item["file"] for item in private_script_headers],
        "qtscript_includes": sorted(private_include_counter),
        "qtscript_identifiers": sorted(private_ident_counter),
        "private_bridge_headers": sorted({inc for inc in private_include_counter if "qscriptdeclarativeclass" in inc}),
        "headers_using_private_bridge": [item["file"] for item in private_script_headers if item["uses_private_bridge"]],
    }

    data = {
        "public_header_count": len(public_headers),
        "private_header_count": len(private_headers),
        "public_headers_with_script_coupling": len(public_script_headers),
        "private_headers_with_script_coupling": len(private_script_headers),
        "public_manifest": public_manifest,
        "private_manifest": private_manifest,
        "public_script_headers": public_script_headers,
        "private_script_headers": private_script_headers,
    }

    DOC_JSON.parent.mkdir(parents=True, exist_ok=True)
    DOC_JSON.write_text(json.dumps(data, indent=2), encoding="utf-8")

    lines: list[str] = []
    lines.append("# BML Script API Manifest\n")
    lines.append("This document is generated by `scripts/generate_bml_script_manifest.py`. It identifies which declarative public/private headers force BTK to provide Script-era API surface before BML can become buildable.\n")
    lines.append("## Headline counts\n")
    lines.append(f"- Declarative public headers scanned: {len(public_headers)}")
    lines.append(f"- Declarative private headers scanned: {len(private_headers)}")
    lines.append(f"- Public headers with Script coupling: {len(public_script_headers)}")
    lines.append(f"- Private headers with Script coupling: {len(private_script_headers)}")
    lines.append("")
    lines.append("## Public Script-facing declarative headers\n")
    lines.append("These headers matter most for downstream source compatibility because they are part of the exposed `QtDeclarative`/BML surface.\n")
    for item in public_script_headers:
        lines.append(f"- `{item['file']}`")
        if item["includes"]:
            lines.append(f"  - includes: {', '.join(f'`{inc}`' for inc in item['includes'])}")
        if item["identifiers"]:
            idents = ", ".join(f"`{name}` ({count})" for name, count in item["identifiers"].items())
            lines.append(f"  - identifiers: {idents}")
    lines.append("")
    lines.append("## Private Script-facing declarative headers\n")
    lines.append("These headers matter for compiler bring-up of `CsDeclarative`, even before downstream packaging is considered.\n")
    for item in private_script_headers:
        lines.append(f"- `{item['file']}`")
        if item["includes"]:
            lines.append(f"  - includes: {', '.join(f'`{inc}`' for inc in item['includes'])}")
        if item["identifiers"]:
            idents = ", ".join(f"`{name}` ({count})" for name, count in item["identifiers"].items())
            lines.append(f"  - identifiers: {idents}")
        if item["uses_private_bridge"]:
            lines.append("  - uses private declarative/script bridge machinery")
    lines.append("")
    lines.append("## Minimum Script manifest interpretation\n")
    lines.append("### Downstream/public compatibility minimum")
    lines.append("BTK will need, at minimum, public Script headers/types sufficient for declarative public headers that reference `QScript*` symbols. The exposed pressure is concentrated around:")
    for header in public_manifest["notable_public_headers"]:
        lines.append(f"- `{header}`")
    lines.append("")
    lines.append("### Declarative compiler bring-up minimum")
    lines.append("In addition to public Script APIs, `CsDeclarative` needs private bridge support, especially:")
    for header in private_manifest["private_bridge_headers"]:
        lines.append(f"- `{header}`")
    lines.append("- `QScriptDeclarativeClass`")
    lines.append("")
    lines.append("### Practical reading\n")
    lines.append("- Public compatibility alone is not enough. Even if BTK provided a minimal `qscriptvalue.h`, declarative internals would still fail without the bridge layer.")
    lines.append("- The first viable `CsScript` restoration pass should therefore be split into two checkpoints: public header compatibility first, then private declarative bridge support for `CsDeclarative` compilation.\n")

    DOC_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
