from __future__ import annotations

import json
import os
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC_MD = ROOT / "docs" / "ai" / "implementation" / "2026-04-04-public-api-rename-inventory.md"
DOC_JSON = ROOT / "docs" / "ai" / "implementation" / "2026-04-04-public-api-rename-inventory.json"

TEXT_SUFFIXES = {
    ".h", ".hpp", ".hh", ".hxx", ".c", ".cc", ".cpp", ".cxx",
    ".cmake", ".txt", ".md", ".in", ".qml", ".rc", ".qrc", ".ui"
}
EXCLUDE_DIRS = {".git", "external", "build", "build-min", "logs", ".tmp-cmake-alias-test", "__pycache__"}

CS_TOKEN_RE = re.compile(r"\b(Cs[A-Z][A-Za-z0-9_]*)\b")
ADD_LIBRARY_RE = re.compile(r"add_library\((Cs[A-Za-z0-9_]+)")
ADD_ALIAS_RE = re.compile(r"add_library\((CopperSpice::Cs[A-Za-z0-9_]+)\s+ALIAS\s+(Cs[A-Za-z0-9_]+)\)")
NAMESPACE_RE = re.compile(r"namespace\s+(Cs(?:String|Pointer|Signal|LibGuarded))\b")


def iter_files(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for filename in filenames:
            path = Path(dirpath) / filename
            if path.suffix.lower() in TEXT_SUFFIXES or filename in {"CMakeLists.txt", "README.md"}:
                yield path


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def main() -> None:
    counts = Counter()
    cs_token_counts: Counter[str] = Counter()
    cs_token_files: dict[str, set[str]] = defaultdict(set)
    cs_prefix_files: list[str] = []
    library_targets: list[str] = []
    alias_targets: list[tuple[str, str]] = []
    annex_namespaces: set[str] = set()
    by_top_dir: Counter[str] = Counter()

    for path in iter_files(ROOT):
        rel = path.relative_to(ROOT).as_posix()
        text = read_text(path)
        if not text:
            continue

        counts["CopperSpice"] += text.count("CopperSpice")
        counts["copperspice"] += text.count("copperspice")
        counts["BTK"] += text.count("BTK")
        counts["btk"] += text.count("btk")

        if path.name.startswith("cs_"):
            cs_prefix_files.append(rel)

        for token in CS_TOKEN_RE.findall(text):
            cs_token_counts[token] += 1
            cs_token_files[token].add(rel)

        for match in ADD_LIBRARY_RE.findall(text):
            library_targets.append(match)

        alias_targets.extend(ADD_ALIAS_RE.findall(text))
        annex_namespaces.update(NAMESPACE_RE.findall(text))

        top_dir = rel.split("/", 1)[0]
        by_top_dir[top_dir] += len(CS_TOKEN_RE.findall(text))

    library_targets = sorted(set(library_targets))
    alias_targets = sorted(set(alias_targets))
    cs_prefix_files = sorted(set(cs_prefix_files))
    top_symbols = [
        {
            "symbol": symbol,
            "references": count,
            "files": len(cs_token_files[symbol]),
        }
        for symbol, count in cs_token_counts.most_common(40)
    ]

    data = {
        "root": str(ROOT),
        "brand_counts": dict(counts),
        "cmake_library_targets": library_targets,
        "cmake_alias_targets": [{"alias": alias, "target": target} for alias, target in alias_targets],
        "annex_namespaces": sorted(annex_namespaces),
        "cs_prefix_file_count": len(cs_prefix_files),
        "cs_prefix_file_samples": cs_prefix_files[:80],
        "top_cs_symbols": top_symbols,
        "cs_token_count_by_top_dir": dict(by_top_dir.most_common()),
    }

    DOC_JSON.parent.mkdir(parents=True, exist_ok=True)
    DOC_JSON.write_text(json.dumps(data, indent=2), encoding="utf-8")

    lines: list[str] = []
    lines.append("# Public API Rename Inventory\n")
    lines.append("This document is generated by `scripts/generate_btk_api_inventory.py`. It inventories high-level `CopperSpice` / `Cs*` naming pressure in the repository while excluding `external/` reference submodules.\n")
    lines.append("## Brand Token Counts\n")
    for key in ["CopperSpice", "copperspice", "BTK", "btk"]:
        lines.append(f"- `{key}`: {counts[key]}")
    lines.append("")
    lines.append("## CMake Library Targets Using `Cs*` Names\n")
    for target in library_targets:
        lines.append(f"- `{target}`")
    lines.append("")
    lines.append("## Existing `CopperSpice::Cs*` Alias Targets\n")
    for alias, target in alias_targets:
        lines.append(f"- `{alias}` -> `{target}`")
    lines.append("")
    lines.append("## Annex Namespace Buckets\n")
    for ns in sorted(annex_namespaces):
        lines.append(f"- `{ns}`")
    lines.append("")
    lines.append(f"## `cs_` File Prefix Count\n- Total files: {len(cs_prefix_files)}\n")
    lines.append("### Sample `cs_`-prefixed files\n")
    for rel in cs_prefix_files[:40]:
        lines.append(f"- `{rel}`")
    lines.append("")
    lines.append("## Top `Cs*` Symbols by Reference Count\n")
    lines.append("| Symbol | References | Files |")
    lines.append("|---|---:|---:|")
    for item in top_symbols:
        lines.append(f"| `{item['symbol']}` | {item['references']} | {item['files']} |")
    lines.append("")
    lines.append("## `Cs*` Token Distribution by Top-Level Directory\n")
    lines.append("| Directory | `Cs*` token matches |")
    lines.append("|---|---:|")
    for directory, value in by_top_dir.most_common():
        lines.append(f"| `{directory}` | {value} |")
    lines.append("")
    lines.append("## Migration Interpretation\n")
    lines.append("- `CsCore`, `CsGui`, `CsNetwork`, and sibling library target names are good candidates for staged BTK target aliasing before deep renames.")
    lines.append("- Annex namespaces (`CsString`, `CsPointer`, `CsSignal`, `CsLibGuarded`) are API-sensitive and should be migrated via compatibility wrappers/typedefs rather than abrupt replacement.")
    lines.append("- `cs_` file prefixes are widespread enough that file-system renames should be deferred until after alias-based API stabilization.")
    lines.append("- Remaining `CopperSpice` branding is still extensive and should be attacked in phases: package/config/docs first, public API second, file names/install layout last.")
    lines.append("")
    DOC_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
