from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT_CMAKE = ROOT / "src" / "script" / "CMakeLists.txt"
WEBKIT_CMAKE = ROOT / "src" / "webkit" / "CMakeLists.txt"
DOC_MD = ROOT / "docs" / "ai" / "implementation" / "2026-04-05-csscript-jscore-drift-audit.md"
DOC_JSON = ROOT / "docs" / "ai" / "implementation" / "2026-04-05-csscript-jscore-drift-audit.json"
TOKEN = "${CMAKE_SOURCE_DIR}/src/3rdparty/webkit/Source/JavaScriptCore"
PATH_RE = re.compile(r"\$\{CMAKE_SOURCE_DIR\}/src/3rdparty/webkit/Source/JavaScriptCore[^\s)\"]+")


def normalize(token: str) -> str:
    return token.replace("${CMAKE_SOURCE_DIR}/", "")


def collect_paths(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    return sorted(set(normalize(match) for match in PATH_RE.findall(text)))


def main() -> None:
    script_paths = collect_paths(SCRIPT_CMAKE)
    webkit_paths = collect_paths(WEBKIT_CMAKE)
    script_set = set(script_paths)
    webkit_set = set(webkit_paths)

    missing = []
    existing = []
    for rel in script_paths:
        p = ROOT / rel
        item = {
            "path": rel,
            "exists": p.exists(),
            "is_file": p.is_file(),
            "is_dir": p.is_dir(),
            "in_webkit_cmake": rel in webkit_set,
        }
        if p.exists():
            existing.append(item)
        else:
            missing.append(item)

    def subtree(rel: str) -> str:
        marker = "src/3rdparty/webkit/Source/JavaScriptCore/"
        if marker in rel:
            tail = rel.split(marker, 1)[1]
            return tail.split("/", 1)[0]
        return rel

    missing_by_subtree = Counter(subtree(item["path"]) for item in missing)
    existing_by_subtree = Counter(subtree(item["path"]) for item in existing)

    data = {
        "script_reference_count": len(script_paths),
        "webkit_reference_count": len(webkit_paths),
        "script_paths_existing": len(existing),
        "script_paths_missing": len(missing),
        "script_paths_also_in_webkit_cmake": sum(1 for item in existing if item["in_webkit_cmake"]),
        "missing_by_subtree": dict(missing_by_subtree.most_common()),
        "existing_by_subtree": dict(existing_by_subtree.most_common()),
        "missing_samples": missing[:120],
        "existing_samples": existing[:120],
    }

    DOC_JSON.parent.mkdir(parents=True, exist_ok=True)
    DOC_JSON.write_text(json.dumps(data, indent=2), encoding="utf-8")

    lines: list[str] = []
    lines.append("# CsScript JavaScriptCore Drift Audit\n")
    lines.append("This document is generated by `scripts/generate_csscript_jscore_drift_audit.py`. It compares the restored historical `src/script/CMakeLists.txt` JavaScriptCore expectations against the current WebKit-embedded JavaScriptCore tree.\n")
    lines.append("## Headline counts\n")
    lines.append(f"- JavaScriptCore path references in restored `src/script/CMakeLists.txt`: {len(script_paths)}")
    lines.append(f"- JavaScriptCore path references in current `src/webkit/CMakeLists.txt`: {len(webkit_paths)}")
    lines.append(f"- Restored Script references currently existing in-tree: {len(existing)}")
    lines.append(f"- Restored Script references currently missing in-tree: {len(missing)}")
    lines.append(f"- Existing restored Script references that also appear in `src/webkit/CMakeLists.txt`: {sum(1 for item in existing if item['in_webkit_cmake'])}")
    lines.append("")
    lines.append("## Missing reference clusters\n")
    lines.append("| Subtree | Missing references |")
    lines.append("|---|---:|")
    for name, count in missing_by_subtree.most_common():
        lines.append(f"| `{name}` | {count} |")
    lines.append("")
    lines.append("## Existing reference clusters\n")
    lines.append("| Subtree | Existing references |")
    lines.append("|---|---:|")
    for name, count in existing_by_subtree.most_common():
        lines.append(f"| `{name}` | {count} |")
    lines.append("")
    lines.append("## Representative missing references\n")
    for item in missing[:40]:
        lines.append(f"- `{item['path']}`")
    lines.append("")
    lines.append("## Interpretation\n")
    lines.append("- The restored historical Script baseline already aligns with a large portion of the current WebKit-embedded JavaScriptCore tree, which validates the recovery-first strategy.")
    lines.append("- The remaining drift is concentrated in legacy subtrees and files expected by historical Script but absent from the current WebKit snapshot, especially older `pcre`, `wrec`, and selected runtime-era files.")
    lines.append("- This means Stage A should continue as an adaptation exercise, not a provenance exercise: the module is back, but its JavaScriptCore contract must now be narrowed or translated to match the modern embedded tree.\n")

    DOC_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
