set(BTK_VERSION_MAJOR "@BUILD_MAJOR@" PARENT_SCOPE)
set(BTK_VERSION_MINOR "@BUILD_MINOR@" PARENT_SCOPE)
set(BTK_VERSION_PATCH "@BUILD_MICRO@" PARENT_SCOPE)

set(BTK_VERSION       "@BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_MICRO@" PARENT_SCOPE)
set(BTK_VERSION_API   "@BUILD_MAJOR@.@BUILD_MINOR@" PARENT_SCOPE)

set(PACKAGE_VERSION "@BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_MICRO@")

if (MSVC OR "${CS_CHECK_BUILD_TYPE}")
   set(PACKAGE_VERSION_COMPATIBLE false)

   set(Debug_Types "Debug" "")

   if ("${CMAKE_BUILD_TYPE}" IN_LIST Debug_Types)
      if ("@CMAKE_BUILD_TYPE@" IN_LIST Debug_Types)
         set(PACKAGE_VERSION_COMPATIBLE true)
      endif()
   endif()

   set(Release_Types "Release" "MinSizeRel" "RelWithDebInfo")

   if ("${CMAKE_BUILD_TYPE}" IN_LIST Release_Types)
      if ("@CMAKE_BUILD_TYPE@" IN_LIST Release_Types)
         set(PACKAGE_VERSION_COMPATIBLE true)
      endif()
   endif()

   if (NOT ${PACKAGE_VERSION_COMPATIBLE})
      set(PACKAGE_VERSION_UNSUITABLE true)
   endif()
endif()

if (PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
   set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
   set(PACKAGE_VERSION_COMPATIBLE TRUE)

   if (PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
      set(PACKAGE_VERSION_EXACT TRUE)
   endif()
endif()
